const productos = [
    {
        "id": 1,
        "producto": "TV Led 50",
        "precio": 100000,
        "fechaVencimiento": "N/A",
        "descripcion": "Televisor Led Smart 50 pulgadas - Noblex",
        "categoria": "Electro",
        "oferta": true,
    },{
        "id": 2,
        "producto": "Mountain bike",
        "precio": 56000,
        "fechaVencimiento": "N/A",
        "descripcion": "Mountain bike Battle 210 R29 18 frenos de disco mecánico cambios Shimano Altus",
        "categoria": "Deportes",
        "oferta": true,
    },{
        "id": 3,
        "producto": "Samsung Galaxy A22",
        "precio": 80000,
        "fechaVencimiento": "N/A",
        "descripcion": "Samsung Galaxy A22 5G 128 GB white 4 GB RAM",
        "categoria": "Celulares",
        "oferta": false,
    },{
        "id": 4,
        "producto": "Moto G82",
        "precio": 95000,
        "fechaVencimiento": "N/A",
        "descripcion": "Moto G82 5G 128 GB blanco 6 GB RAM",
        "categoria": "Celulares",
        "oferta": true,
    },{
        "id": 5,
        "producto": "Moto G52",
        "precio": 76000,
        "fechaVencimiento": "N/A",
        "descripcion": "Moto G52 128 GB azul 6 GB RAM",
        "categoria": "Celulares",
        "oferta": false,
    },{
        "id": 6,
        "producto": "Cerveza Patagonia Amber",
        "precio": 9000,
        "fechaVencimiento": "10/11/2023",
        "descripcion": "Cerveza Patagonia Amber Lager 410ml X24",
        "categoria": "Bebidas alcohólicas",
        "oferta": false,
    },{
        "id": 7,
        "producto": "Cerveza Andes Rubia",
        "precio": 5000,
        "fechaVencimiento": "07/06/2023",
        "descripcion": "Cerveza Andes Origen Rubia 473ml X24",
        "categoria": "Bebidas alcohólicas",
        "oferta": true,
    },{
        "id": 8,
        "producto": "Whisky Jameson",
        "precio": 7000,
        "fechaVencimiento": "15/03/2026",
        "descripcion": "Whiskey Jameson Caskmates Ipa 700ml",
        "categoria": "Bebidas alcohólicas",
        "oferta": false,
    },{
        "id": 9,
        "producto": "Licuadora Philips",
        "precio": 11500,
        "fechaVencimiento": "N/A",
        "descripcion": "Licuadora Philips Daily Collection HR2126 1.5 L negra con jarra de plástico 220V",
        "categoria": "Electro",
        "oferta": true,
    },{
        "id": 10,
        "producto": "Cinta de correr Reebok",
        "precio": 380000,
        "fechaVencimiento": "N/A",
        "descripcion": "Cinta de correr eléctrica Reebok Jet 200+ with Bluetooth 220V negra y roja",
        "categoria": "Deportes",
        "oferta": true,
    },{
        "id": 11,
        "producto": "Remera Adidas",
        "precio": 7500,
        "fechaVencimiento": "N/A",
        "descripcion": "Remera Essentials Logo Pequeño Bordado Negro adidas",
        "categoria": "Indumentaria",
        "oferta": false,
    },{
        "id": 12,
        "producto": "Pantalón Adidas",
        "precio": 22000,
        "fechaVencimiento": "N/A",
        "descripcion": "Pantalón Own The Run Astro Wind adidas",
        "categoria": "Indumentaria",
        "oferta": true,
    },{
        "id": 13,
        "producto": "Zapatillas Adidas",
        "precio": 21900,
        "fechaVencimiento": "N/A",
        "descripcion": "Zapatillas Duramo Sl-negro adidas",
        "categoria": "Indumentaria",
        "oferta": false,
    },{
        "id": 14,
        "producto": "Bocadito Marroc",
        "precio": 3900,
        "fechaVencimiento": "17/03/2023",
        "descripcion": "Bocadito Marroc Felfort 60 Unidades",
        "categoria": "Almacén",
        "oferta": true,
    },{
        "id": 15,
        "producto": "Café instantaneo Nescafé",
        "precio": 1500,
        "fechaVencimiento": "23/10/2023",
        "descripcion": "Café instantáneo clásico Nescafé Gold frasco 100gr",
        "categoria": "Almacén",
        "oferta": false,
    }    
]